import { test, expect } from '@playwright/test'
import { registerSession } from './helpers/session'

test('employee publishes, supports, withdraws and maintains a scenario contribution', async ({ page }, testInfo) => {
  await page.addInitScript(() => window.localStorage.setItem('i18nextLng', 'zh'))
  await registerSession(page, testInfo)
  await page.goto('/demands')
  await expect(page.getByRole('heading', { name: '需求广场', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '发布需求', exact: true }).click()
  const title = `订单异常整理 ${Date.now()}`
  await page.getByLabel('需求标题 *').fill(title)
  await page.getByLabel('业务场景与痛点 *').fill('每天需要合并多个店铺的订单，人工检查重复记录。')
  await page.getByLabel('期望结果 *').fill('按订单号去重，生成需要人工核查的异常清单。')
  await page.getByLabel('业务分类 · 选填').fill('订单运营')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page).toHaveURL(/\/demands\/\d+$/)
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  await page.getByRole('button', { name: '我也需要 · 0' }).click()
  await expect(page.getByRole('button', { name: '已支持 · 1' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '已支持 · 1' }).click()
  await expect(page.getByRole('button', { name: '我也需要 · 0' })).toBeVisible()
  await page.getByLabel('补充你的使用场景、与原需求的差异，或希望获得的结果。').fill('还需要区分退款订单，输出退款原因。')
  await page.getByRole('button', { name: '提交场景补充' }).click()
  const contribution = page.getByRole('article').filter({ hasText: '还需要区分退款订单' })
  await expect(contribution).toBeVisible()
  await expect(page.getByRole('button', { name: '我也需要 · 0' })).toBeVisible()
  await contribution.getByRole('button', { name: '编辑', exact: true }).click()
  await contribution.getByRole('textbox').fill('还需要区分退款订单，并保留订单号。')
  await contribution.getByRole('button', { name: '保存', exact: true }).click()
  await expect(contribution.getByRole('textbox')).toHaveCount(0)
  await expect(contribution.getByText('还需要区分退款订单，并保留订单号。', { exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('demand-detail.png'), fullPage: true })
  await contribution.getByRole('button', { name: '删除', exact: true }).click()
  await contribution.getByRole('button', { name: '删除', exact: true }).last().click()
  await expect(page.getByText('还没有场景补充。', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '← 返回需求广场' }).click()
  await page.getByRole('textbox', { name: '搜索标题或业务场景' }).fill(title)
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(page.getByRole('link', { name: title })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('demand-square.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('link', { name: '需求广场', exact: true }).filter({ visible: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('demand-mobile.png'), fullPage: true })
})
